---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: task-tool
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./app/k8s/v3-ans/overlays/prod
  prune: true
  sourceRef:
    kind: GitRepository
    name: task-tool
  targetNamespace: prod
  patches:
    - patch: |
        apiVersion: apps/v1
        kind: Deployment
        metadata:
          name: task-web
          namespace: prod
        spec:
          replicas: 5
      target:
        kind: Deployment
        name: task-web

