apiVersion: v1
kind: PersistentVolume
metadata:
  name: ebs-test-volume
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  # CSI設定
  csi:
    driver: ebs.csi.aws.com
    # 手動作成したEBSのVolumeID
    volumeHandle: vol-00b52f41e6065cb7c
