apiVersion: v1
kind: ConfigMap
metadata:
  name: localstack-init-scripts-config
data:
  # AWS Credential情報初期化
  01-credential.sh: |
    #!/bin/bash
    aws configure set aws_access_key_id localstack
    aws configure set aws_secret_access_key localstack
    aws configure set region local
    export LOCALSTACK_ENDPOINT=http://localhost:4566
  # S3バケット作成
  02-create-bucket.sh: |
    #!/bin/bash
    aws s3api create-bucket --bucket localstack-test-bucket --endpoint ${LOCALSTACK_ENDPOINT}
    aws s3api list-buckets --endpoint ${LOCALSTACK_ENDPOINT}
  # DynamoDBテーブル作成
  03-create-dynamodb-table.sh: |
    #!/bin/bash
    aws dynamodb create-table --table-name localstack-test \
      --key-schema  AttributeName=test_key,KeyType=HASH \
      --attribute-definitions AttributeName=test_key,AttributeType=S \
      --billing-mode PAY_PER_REQUEST \
      --endpoint ${LOCALSTACK_ENDPOINT}
    aws dynamodb list-tables --endpoint ${LOCALSTACK_ENDPOINT} --region local
